const eventsArr = [
  "CALLER_DESCRIPTION_SENT",
  "INCOMING_REMOTE_DESCRIPTION",
  "USER_LIST",
  "USER_ALREADY_EXIST",
  "SEND_CALLER_ICE",
  "INCOMING_CALLER_ICE",
  "SEND_CALLEE_ICE",
  "INCOMING_CALLEE_ICE",
  "CALLEE_CALL_REJECTED",
  "DISCONNECT",
  "USER_REGISTERED",
  "USER_UNREGISTERED",
  "SEND_CALLER_CALLING",
  "INCOMING_CALLER_CALLING",
  "SEND_CALLEE_CALL_ACCEPTED",
  "INCOMING_CALLEE_CALL_ACCEPTED",
  "SEND_CALLER_OFFER",
  "INCOMING_CALLER_OFFER",
  "SEND_CALLEE_ANSWER",
  "INCOMING_CALLEE_ANSWER",
  "SEND_CALLER_END_CALL",
  "INCOMING_CALLER_END_CALL",
  "SEND_CALLEE_END_CALL",
  "INCOMING_CALLEE_END_CALL",
  "SEND_CALLEE_CALL_REJECTED",
  "INCOMING_CALLEE_CALL_REJECTED",
];

const websocket = {};

eventsArr.forEach((event) => {
  websocket[event] = event.toLowerCase();
});

module.exports = websocket;
